name: Arduino Remote Compile
on:
  repository_dispatch:
    types: [compile_cmd]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile Sketch
        run: |
          mkdir -p build_sketch
          cat << 'ARDUINO_SKETCH_END' > build_sketch/build_sketch.ino
          ${{ github.event.client_payload.code }}
          ARDUINO_SKETCH_END
          
          arduino-cli compile --fqbn arduino:avr:uno build_sketch --output-dir ./out

      - name: Push Firmware to builds branch
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin builds || true
          git checkout -B builds
          cp out/build_sketch.ino.hex firmware.hex
          git add firmware.hex
          git commit -m "Update firmware: ${{ github.event.client_payload.timestamp }}" || echo "No changes"
          git push origin builds --force
